
services:
  strapi:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: strapi
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: db-strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: js4life
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
      - ./entrypoint.sh:/opt/app/entrypoint.sh
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: db-strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: js4life
    volumes:
      - ./data:/var/lib/postgresql/data

  
