
services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: db-strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: js4life
    volumes:
      - ./data:/var/lib/postgresql/data

