
services:
  strapi:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: strapi
    ports:
      - '1337:1337'
    working_dir: /app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: db-strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: js4life
    volumes:
      - /home/julek/docker/strapi-starter-project/app:/opt/app/config
      - /home/julek/docker/strapi-starter-project/config:/opt/app/config
      - /home/julek/docker/strapi-starter-project/src:/opt/app/src
      - /home/julek/docker/strapi-starter-project/package.json:/opt/app/package.json
      - /home/julek/docker/strapi-starter-project/yarn.lock:/opt/app/yarn.lock
      - /home/julek/docker/strapi-starter-project/.env:/opt/app/.env
      - /home/julek/docker/strapi-starter-project/public/uploads:/opt/app/public/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: db-strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: js4life
    volumes:
      - /home/julek/docker/strapi-project/data:/var/lib/postgresql/data

  
